name: style

on:
  push:
    branches: [ "main" ]
    paths:
      - '.github/workflows/*.yml'
      - '**/*.py'
      - 'pyproject.toml'

  pull_request:
    paths:
      - '.github/workflows/*.yml'
      - '**/*.py'
      - 'pyproject.toml'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Helps prevent parallel runs of the workflow from overlapping
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

# Write permissions are not needed for this workflow
permissions: {}

jobs:
  style:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install mdb and additional python packages
        run: |
          pip install -e .[develop]
      - name: Run black  # check code is compliant with black formatting
        run: |
          black --check .
      - name: Run flake8 # check for flake8 compliance
        run: |
          flake8 .
      - name: Run mypy # static type analysis
        run: |
          mypy --strict .
