name: style

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  style:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v5
      with:
        python-version: '3.11'
    - name: Install mdb and additional python packages
      run: |
        pip install -e .[develop]
    - name: Run black  # check code is compliant with black formatting
      run: |
        black --check .
    - name: Run flake8 # check for flake8 compliance
      run: |
        flake8 .
    - name: Run mypy # static type analysis
      run: |
        mypy --strict .
