name: style

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v5
      with:
        python-version: '3.11'
    - name: Install Python Packages
      run: |
        pip install black flake8
        black .                # check code is compliant with black formatting
        flake8 --ignore=E501 . # check for flake8 compliance but ignore E501 (line-length)
