name: tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  validate:
    runs-on: ubuntu-latest
    timeout-minutes: 3
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v5
      with:
        python-version: '3.11'
    - name: Install system dependencies
      run: |
        sudo apt update
        sudo apt install -y gdb libopenmpi-dev libssl-dev lldb
    - name: Build example mpi program
      run: |
        make -C examples/
    - name: Install mdb and additional python packages
      run: |
        pip install -e .[develop,termgraph]
    - name: Setup tmate session
      uses: mxschmitt/action-tmate@v3
      run: |
        git clone https://github.com/TomMelt/dotfiles.git ~/.dotfiles
        ln -sf ~/.dotfiles/.tmux.conf .
    - name: Run tests
      run: |
        pytest --cov-report term-missing --cov-report json:cov.json --cov=mdb -vv tests/
    - name: Check coverage
      run: |
        python .github/workflows/coverage.py 60
    # - name: Setup tmate session
    #   uses: mxschmitt/action-tmate@v3
