name: tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v5
      with:
        python-version: '3.11'
    - name: Install gdb gdbserver openmpi
      run: |
        sudo apt update
        sudo apt install -yq gdb gdbserver libopenmpi-dev
    - name: Build example mpi program
      run: |
        make -C examples/
    - name: Install mdb and additional python packages
      run: |
        pip install -e .[develop,termgraph]
    - name: Run tests
      run: |
        pytest --cov-report term-missing --cov-report json:cov.json --cov=mdb -vv tests/
    - name: Check coverage
      run: |
        python .github/workflows/coverage.py 60
